name: Deploy static content to Pages

on:
  push:
    branches: ['main'] # Change to your branch name

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      pages: write
      id-token: write
    steps:
      - uses: actions/checkout@v4
      # Create a .nojekyll file to prevent Jekyll processing
      - run: touch .nojekyll
      - uses: actions/upload-pages-artifact@v3
        with:
          path: '.' # Defines the directory to upload
      - uses: actions/deploy-pages@v4
